# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    filePath: './Build/build.ps1'
  
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: 'Artifacts\NuGet\UnitsNet.*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'c38893ab-a5c1-49f6-9ed7-af60abdc9e00'
   

    


